# Generated by Django 4.2.1 on 2023-05-24 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='product')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amout', models.PositiveIntegerField()),
                ('min_amout', models.PositiveSmallIntegerField()),
                ('uni', models.CharField(choices=[('un', 'unidade'), ('kg', 'kilograma'), ('gr', 'grama'), ('dz', 'duzia'), ('m2', 'metro quadrado'), ('m3', 'metro cubico'), ('mt', 'metro'), ('lt', 'litro')], max_length=20)),
                ('category', models.ForeignKey(default='Sem categoria', on_delete=django.db.models.deletion.SET_DEFAULT, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_movement', models.CharField(choices=[('ENTRY', 'entry'), ('OUTPUT', 'output')], max_length=10)),
                ('amout', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
